import type { ServiceCategory, ServicePackage } from "@/types/portfolio";

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    title: "Website Development",
    items: [
      "Business websites",
      "Portfolio websites",
      "Landing pages",
      "Personal brand websites",
      "Company profile websites",
      "Blog platforms",
      "CMS-based websites",
      "Marketing websites",
      "Event websites",
      "Educational websites",
      "NGO or community websites",
    ],
  },
  {
    title: "Web Application Development",
    items: [
      "SaaS platforms",
      "Admin dashboards",
      "CRM systems",
      "ERP-lite systems",
      "Appointment booking systems",
      "Inventory management systems",
      "Employee management portals",
      "Lead management systems",
      "Customer portals",
      "Subscription platforms",
      "Multi-role applications",
      "Internal company tools",
    ],
  },
  {
    title: "E-Commerce Development",
    items: [
      "Custom e-commerce stores",
      "Product catalog websites",
      "Shopping cart and checkout systems",
      "Payment gateway integration",
      "Order management dashboard",
      "Coupon and discount systems",
      "Inventory tracking",
      "Vendor marketplace platforms",
      "Multi-vendor e-commerce",
      "Subscription commerce platforms",
      "Delivery tracking integration",
    ],
  },
  {
    title: "Mobile App Development",
    items: [
      "React Native mobile apps",
      "Expo applications",
      "Android apps",
      "iOS apps",
      "Cross-platform applications",
      "Business management apps",
      "E-learning apps",
      "Booking apps",
      "Fitness apps",
      "Food delivery apps",
      "Marketplace apps",
      "Social/community apps",
    ],
  },
  {
    title: "Backend Development",
    items: [
      "REST API development",
      "Node.js and Express backend",
      "Authentication systems",
      "Role-based access control",
      "Database design",
      "PostgreSQL development",
      "Firebase backend",
      "File upload systems",
      "Payment integrations",
      "Notification systems",
      "Email/SMS integrations",
      "Third-party API integrations",
    ],
  },
  {
    title: "Frontend Development",
    items: [
      "React applications",
      "Next.js applications",
      "TypeScript frontend development",
      "Responsive website development",
      "Dashboard UI development",
      "Component library development",
      "Design-to-code conversion",
      "Figma to React conversion",
      "Performance optimization",
      "Accessibility improvements",
      "SEO-friendly frontend implementation",
    ],
  },
  {
    title: "UI/UX Implementation",
    items: [
      "Modern UI design implementation",
      "Responsive layouts",
      "Mobile-first interfaces",
      "Design system creation",
      "Reusable component architecture",
      "Form design and validation",
      "Dashboard design",
      "Data table interfaces",
      "Empty states and error states",
      "Loading skeletons",
      "Dark mode implementation",
    ],
  },
  {
    title: "Authentication and Security",
    items: [
      "Email/password authentication",
      "Phone OTP authentication",
      "Social login integration",
      "Google login",
      "Firebase Authentication",
      "JWT authentication",
      "Session management",
      "Role-based permissions",
      "Admin/user access systems",
      "Secure API protection",
      "Input validation with Zod",
      "Rate limiting and security hardening",
    ],
  },
  {
    title: "Database Services",
    items: [
      "PostgreSQL database design",
      "Database schema design",
      "Supabase setup",
      "Firebase Firestore setup",
      "Data migration scripts",
      "Database optimization",
      "Query optimization",
      "Backup strategy setup",
      "User and role management",
      "Reporting database structures",
    ],
  },
  {
    title: "API and Integration Services",
    items: [
      "REST API integration",
      "Payment gateway integration",
      "Razorpay integration",
      "Stripe integration",
      "PayPal integration",
      "Google Maps integration",
      "WhatsApp API integration",
      "SMS API integration",
      "Email service integration",
      "Firebase Cloud Messaging",
      "Analytics integration",
      "CRM integration",
      "Shipping API integration",
    ],
  },
  {
    title: "Admin Dashboard Development",
    items: [
      "User management dashboard",
      "Product management dashboard",
      "Order management panel",
      "Content management dashboard",
      "Analytics dashboard",
      "Sales dashboard",
      "Role and permission management",
      "Report generation",
      "Export CSV/Excel functionality",
      "Activity logs",
      "Settings management panel",
    ],
  },
  {
    title: "Maintenance and Support",
    items: [
      "Bug fixing",
      "Feature enhancements",
      "Performance optimization",
      "Security updates",
      "Dependency upgrades",
      "UI improvements",
      "API fixes",
      "Database fixes",
      "Production issue resolution",
      "Ongoing monthly maintenance",
      "Monitoring and error tracking setup",
    ],
  },
  {
    title: "Deployment and DevOps",
    items: [
      "Docker containerization",
      "VPS deployment",
      "AWS deployment",
      "Vercel deployment",
      "Render deployment",
      "Railway deployment",
      "Firebase deployment",
      "Supabase deployment",
      "CI/CD setup",
      "Environment variable configuration",
      "Domain and SSL setup",
      "Production optimization",
    ],
  },
  {
    title: "Code Quality and Architecture",
    items: [
      "Project architecture setup",
      "Modular folder structure",
      "Reusable component development",
      "TypeScript migration",
      "Code refactoring",
      "API architecture improvement",
      "State management cleanup",
      "Performance audit",
      "Security audit",
      "Code review",
      "Documentation",
      "Clean code improvements",
    ],
  },
  {
    title: "SEO and Performance",
    items: [
      "Technical SEO setup",
      "Meta tags and Open Graph setup",
      "Sitemap generation",
      "robots.txt setup",
      "Page speed optimization",
      "Image optimization",
      "Core Web Vitals improvements",
      "Server-side rendering with Next.js",
      "Structured data implementation",
      "Google Search Console setup",
      "Google Analytics integration",
    ],
  },
  {
    title: "AI Features for Client Projects",
    items: [
      "AI chatbot integration",
      "Customer support chatbot",
      "AI content generation tools",
      "AI document summarization",
      "AI search functionality",
      "AI-powered recommendation systems",
      "OpenAI API integration",
      "Gemini API integration",
      "AI form assistants",
      "AI-based dashboard insights",
    ],
  },
];

export const SERVICE_PACKAGES: ServicePackage[] = [
  {
    name: "Landing Page Package",
    includes: [
      "Responsive landing page",
      "Contact form",
      "SEO basics",
      "Deployment",
    ],
  },
  {
    name: "Business Website Package",
    includes: [
      "5-10 pages",
      "CMS/admin panel",
      "Contact forms",
      "SEO",
      "Deployment",
    ],
  },
  {
    name: "E-Commerce Package",
    includes: [
      "Product catalog",
      "Cart",
      "Checkout",
      "Payment gateway",
      "Admin dashboard",
    ],
  },
  {
    name: "SaaS MVP Package",
    includes: [
      "Auth",
      "Dashboard",
      "API",
      "Database",
      "Subscriptions",
      "Deployment",
    ],
  },
  {
    name: "Mobile App MVP Package",
    includes: [
      "React Native app",
      "Authentication",
      "API integration",
      "Android/iOS builds",
    ],
  },
  {
    name: "Dashboard Package",
    includes: [
      "Admin panel",
      "Charts",
      "Tables",
      "Role access",
      "CRUD modules",
    ],
  },
  {
    name: "Maintenance Package",
    includes: [
      "Monthly bug fixes",
      "Updates",
      "Monitoring",
      "Small feature changes",
    ],
  },
  {
    name: "API Integration Package",
    includes: [
      "Third-party API setup",
      "Webhook handling",
      "Testing",
      "Documentation",
    ],
  },
];

export const SERVICE_POSITIONING =
  "I build scalable web applications, mobile apps, SaaS platforms, dashboards, e-commerce systems, APIs, and custom business software using React, Next.js, React Native, Node.js, PostgreSQL, Firebase, and TypeScript. I focus on clean architecture, reusable components, secure backend systems, responsive UI, and production-ready deployment.";
